# Generated by Django 3.1.2 on 2020-11-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_title_image',
            field=models.ImageField(upload_to='', verbose_name='Title_image'),
        ),
    ]
