# Generated by Django 3.1.2 on 2020-12-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20201129_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='text',
        ),
    ]
