# Generated by Django 3.1.2 on 2020-12-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20201206_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.CharField(blank=True, max_length=75, verbose_name='author'),
        ),
    ]
