# Generated by Django 3.1.2 on 2020-12-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_image.png', upload_to='avatars'),
        ),
    ]
